baseURL: --
languageCode: en-us
title: 2060
theme: "2060"

menu:
  main:
    - identifier: "Integrate"
      name: Integrate
      url: /integrate
      weight: 10
    - identifier: "Operate"
      name: Operate
      url: /operate
      weight: 20
    - identifier: "About"
      name: About
      url: /about
      weight: 30
