baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '2060 -Welcome to the web of openness'
theme = '2060'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Integrate"
    url = "/integrate"
    weight = 1
  [[menu.main]]
    name = "Operate"
    url = "/operate"
    weight = 2
  [[menu.main]]
    name = "Explore"
    url = ""
    weight = 3
    pre = false