baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"
ignoreErrors: ["error-remote-getjson"]
title: "2060 Web5 Accelerator"

# googleAnalytics: ""

summaryLength: 20

params:
  title: ""
  description: "The Web5 Accelerator"
  images:
    - "images/footer-img/logo-white.svg"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    github: "https://github.com/2060-io"
    linkedin: "#"
    twitter: "#"

  location:
    - "Cra 13A #86A-42, Bogotá DC, Colombia"
    - "Paseo de Recoletos 27-41 Madrid, 28004, Spain"

  contact:
    - "hello@2060.io"
    - "+00 123 456 789"

  copyright: " © 2023 - 2060.io | All Rights Reserved "

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Use Cases"
      url: "/usecases"
      weight: 2

    - name: "About"
      url: "/about"
      weight: 3

    - name: "Contact"
      url: "/contact/"
      weight: 4

  externals:
    - name: "Github"
      url: "https://github.com/2060-io"
      weight: 5
      pre: "github-header mx-2 mb-4 mb-md-0"

  buttons:
    - name: "Download"
      url: "/"
      weight: 6
      pre: "btn btn-green-soft btn-header-download fw-medium px-4 py-2 text-light d-flex align-items-center"

  footer:
    - name: "Our Vision"
      url: "#"
      weight: 1

    - name: "The Team"
      url: "#"
      weight: 2

    - name: "Privacy Policy"
      url: "/privacy"
      weight: 3

taxonomies:
  series: "series"
  tags: "tags"
